### PR TITLE
feat: support delete node

### LINKED ISSUE #126: feat: Support remove a node from the cluster
In some circumstances, one of the server is in a crash status, we can not connect the sever to execute `mdz server stop` or `mdz server remove`. 

I think we can add new command to help the people remove the issue node manually

### PR DESCRIPTION
**Pull request by kemingy**
- close #126

### CODE REVIEW

**Comment by kemingy** [comment]
- CI failed due to https://github.com/tensorchord/openmodelz/pull/138

cc @gaocegege

**Review by gaocegege — APPROVED** [review]

**Comment by gaocegege** [comment]
Test failed.

BTW, please run go run ./hack/cli-doc-gen/main.go to generate the doc.

**Comment by kemingy** [comment]
> Test failed.
> 
> BTW, please run go run ./hack/cli-doc-gen/main.go to generate the doc.

Updated.

The test will fail because the agent is using the old version.

cc @zwpaper

**Comment by zwpaper** [comment]
@kemingy sorry for the later reply, created a issue, let's discuss it here https://github.com/tensorchord/openmodelz/issues/147

**Review by gaocegege — APPROVED** [review]

**Pull request merged**
