### PR TITLE
feat: support follow the k8s log

### LINKED ISSUE #124: feat: support --follow options in `mdz logs command`

### PR DESCRIPTION
**Pull request by kemingy**
- close #124 

This PR adds the `mdz logs <name> --follow` argument.

### CODE REVIEW

**Comment by kemingy** [comment]
The stream log has a delay of about 70s. cc @gaocegege

**Review by gaocegege — APPROVED** [review]

**Comment by kemingy** [comment]
> > The stream log has a delay of about 70s. cc @gaocegege
> 
> Where does it come from?

I have no idea. I suspect it's because the log is retrieved after some delay. Not familiar with Kubernetes logs.

**Comment by kemingy** [comment]
Shall we merge this PR and track it in another issue?

**Comment by gaocegege** [comment]
SGTM!

**Pull request merged**
