### PR TITLE
Revert "build: use build.sh to build mdz"

### PR DESCRIPTION
**Pull request by zwpaper**
Reverts tensorchord/openmodelz#138 

check https://github.com/tensorchord/openmodelz/issues/147

### CODE REVIEW

**Comment by kemingy** [comment]
Please fix the conflicts.

**Comment by zwpaper** [comment]
if we migrate to one go.mod, this should not be necessary. I am closing this one in favor of https://github.com/tensorchord/openmodelz/pull/151#pullrequestreview-1575976492

**Comment by kemingy** [comment]
I think we still need to rever this one since these are no longer required.

**Comment by zwpaper** [comment]
what we need should be only rollback the build logic, created a PR for it https://github.com/tensorchord/openmodelz/pull/154

**Pull request closed without merging**
